config/routes.rb
I18nO7r::Engine.routes.draw do
  root to: 'translations#index'

  get  "translations/(*path)"  => 'translations#index', as: 'translations'
  post "translations/(*path)"  => 'translations#update'
  get "keys/(*path)/edit" => 'keys#edit', as: 'edit_key'
  patch "keys/(*path)" => 'keys#update', as: 'update_key'
  get "keys/(*path)" => 'keys#destroy', as: 'remove_key'
  get  "missing_translations/:lang/(*path)" => 'missing_translations#index', as: 'missing_translations'
  get "search" => 'search#index', as: 'search'
  get "markers" => 'markers#index', as: 'markers'
  post "mark/(*key)" => 'markers#create', as: 'mark'
  delete "unmark/(*key)" => 'markers#destroy', as: 'unmark'
end

app/controllers/i18n_o7r/application_controller.rb
module I18nO7r
  class ApplicationController < ActionController::Base

    raise "Configure I18nO7r before use" unless I18nO7r.configured

    if I18nO7r.username.present? && I18nO7r.password.present?
      http_basic_authenticate_with name: I18nO7r.username, password: I18nO7r.password
    end

    before_action do
      if (!I18nO7r.username || !I18nO7r.password) && Rails.env.production?
        raise "secure I18nO7r with username and password for use in production"
      end
    end

  end
end

app/controllers/i18n_o7r/keys_controller.rb
module I18nO7r
  class KeysController < I18nO7r::ApplicationController

    before_action :gsub_path, only: [:update, :destroy]

    def edit
      @path = params[:path]
      render action: 'edit', layout: false
    end

    def update
      @store = Store.new
      new_key = params[:new_key]
      if new_key.present?
        i18n_o7r_locales.each do |l|
          append = ''
          if @keys.last =~ /~~\z/i
            append = '~~'
          end
          val = @store.for(@keys[0...-1], locale: l).delete @keys.last.to_sym
          @store.for(@keys[0...-1], locale: l)["#{params[:new_key]}#{append}".to_sym] = val
        end
        @store.dump!
        I18n.reload!
        render json: {success: true}
      else
        render json: {success: false}, status: :unprocessable_entity
      end
    end

    def destroy
      @store = Store.new
      i18n_o7r_locales.each do |l|
        @store.for(@keys[0...-1], locale: l).delete @keys.last.to_sym
      end
      @store.dump!
      I18n.reload!
      redirect_to i18n_o7r.translations_path(params[:path].split('/')[0...-1].join('/'))
    end


    private

    def gsub_path
      @keys = (params[:path].try(:split, '/') || []).map{|s|s.gsub('--','/')}
    end
  end
end

app/controllers/i18n_o7r/markers_controller.rb
module I18nO7r
  class MarkersController < I18nO7r::ApplicationController

    before_action :gsub_path, only: [:create, :destroy]

    def create
      @store = Store.new
      I18nO7r.languages.each do |l|
        @store.for(@keys[0...-1], locale: l)["#{@keys.last}~~".to_sym] = @store.for(@keys[0...-1], locale: l)[@keys.last.to_sym]
        @store.for(@keys[0...-1], locale: l).delete @keys.last.to_sym
      end
      @store.dump!
      I18n.reload!
      render json: {success: true}
    end

    def index
      @store = Store.new
      @path = []
      @locals = []
      vv = @store.for([], locale: I18n.default_locale)
      traverse_hash(vv)
    end

    def destroy
      @store = Store.new
      i18n_o7r_locales.each do |l|
        @store.for(@keys[0...-1], locale: l)["#{@keys.last}".gsub(/~~\z/, '').to_sym] = @store.for(@keys[0...-1], locale: l)[@keys.last.to_sym]
        @store.for(@keys[0...-1], locale: l).delete @keys.last.to_sym
      end
      @store.dump!
      I18n.reload!
      render json: {success: true}
    end


    private

    def traverse_hash(hash)
      hash.each do |k,v|
        @path.push k
        if v.is_a?(Hash)
          # do the same thing
          traverse_hash(v)
        else
          if k =~ /~~\z/i
            @locals << {key: @path[0...-1], entry: @path.last, value: v}
          end
        end
        @path.pop
      end
    end

    def gsub_path
      @keys = (params[:key].try(:split, '/') || []).map{|s|s.gsub('--','/')}
    end
  end
end

app/controllers/i18n_o7r/missing_translations_controller.rb
module I18nO7r
  class MissingTranslationsController < I18nO7r::ApplicationController

    def index
      @lang = params[:lang]
      @store = Store.new().unify!
    end

  end
end

app/controllers/i18n_o7r/search_controller.rb
module I18nO7r
  class SearchController < I18nO7r::ApplicationController

    def index
      @value = params[:query]
      redirect_to(request.referrer) && return if @value.length <= 3
      @store = Store.new
      @path = []
      @locals = []
      i18n_o7r_locales.each do |locale|
        vv = @store.for([], locale: locale)
        traverse_hash(vv)
      end
    end

    private

    def traverse_hash(hash)
      hash.each do |k,v|
        @path.push k
        if v.is_a?(Hash)
          # do the same thing
          traverse_hash(v)
        else
          if v =~ /#{@value}/i
            @locals << {key: @path[0...-1], entry: @path.last, value: v}
          end
        end
        @path.pop
      end
    end
  end
end

app/controllers/i18n_o7r/translations_controller.rb
module I18nO7r
  class TranslationsController < I18nO7r::ApplicationController

    before_action do
      @keys = (params[:path].try(:split, '/') || []).map{|s|s.gsub('--','/')}
      @store = Store.new()
    end

    def index
      vv = @store.unify!.for(@keys)
      if vv.present?
        vv = vv.group_by{|k,v| v.is_a?(Hash) && v.present? && (v.keys - [:html]).present? }
        @subtrees = vv[true] || []
        @entries = vv[false] || []
      end
    end

    def update
      @store.unify!
      params[:translations].each do |_, translation|
        translation.each do |lang, locale|
          lstore = @store.for(locale[:key].split('.'), locale: lang)
          if !lstore
            puts "Ignoring: #{locale[:key]}"
          else
            locale[:entry].each do |k, v|
              lstore[k.to_sym] = v.presence
            end
          end
        end
      end
      @store.dump!
      I18n.reload!
      redirect_to params[:return_path] || i18n_o7r.translations_path(params[:path])
    end
  end
end

app/helpers/i18n_o7r/application_helper.rb
module I18nO7r
  module ApplicationHelper
    def i18n_o7r_link_missing_to(path)
      <<-HTML
        <script type="text/javascript">
        $(document).on('click', '.translation_missing[title*="translation missing: "]', function(){
          var node = $(this);
          var t = node.attr('title');
          var p = t.split(': ')[1].split('.').replace(/\//g, '-').slice(1).join('/');

        });
        </script>
      HTML
    end

    def i18n_o7r_translations_path(path_components=[])
      pc = [path_components].flatten
      p = pc.map{|c| c.to_s.gsub('/', '--')}.join('/')
      i18n_o7r.translations_path(p)
    end
  end
end


__END__

translation_missing
title="translation missing: de.shop.application.navbar.logout"

app/views/i18n_o7r/application/_list_panel.html.slim
- n = 0
- if subtrees.present?
  - content_for :buttons
    - subtrees.each do |s, tree|
      li.margin: tt= link_to details_url.(keys + [s]), class: 'btn btn-default'
        - c = tree._deep_count
        - n += c
        = "#{s} (#{c})"
= form_tag form_url, 'data-method' => :post
  .panel class=panel_type
    .panel-heading
      h3.panel-title.i18no7rhead
        => title
      - if show_home_button
        ul.horizontal.nomargin
          li= link_to details_url.(''), class: 'btn btn-default'
            i.glyphicon.glyphicon-home
            = " #{n}"
          - keys.length.times do |i|
            li
              - c = (keys.length == i+1 ? 'btn-primary' : 'btn-default')
              tt= link_to keys[i], details_url.(keys[0..i]), class: "btn #{c}"
    - if subtrees.present?
      .panel-body
        ul.horizontal
          = content_for :buttons
    - if locals.present?
      table.table.table-striped.o7rtable
        tr
          th Key
          - I18nO7r.languages.each do |l|
            th= l
        - locals.each.with_index do |local, ix|
          tr
            td.label-cell
              tt
                span.prefix
                  = (local[:key] + ['']).join('.')
                span.key
                  = local[:entry].to_s.gsub(/~~\z/, '')
                  - if local[:value].is_a?(Hash)
                    | .html
              .pull-right.buttons.modification-buttons
                - full_key = "#{local[:key].map{|s|s.to_s.gsub('/','--')}.join('/')}/#{local[:entry]}"
                .btn-group
                  = link_to edit_key_path(path: full_key), class: 'btn btn-xs btn-primary edit-key', remote: true
                    i.glyphicon.glyphicon-pencil
                  = link_to remove_key_path(path: full_key), class: 'btn btn-xs btn-danger remove-key', data: {confirm: 'Are you sure?'}
                    i.glyphicon.glyphicon-remove
                  - if local[:entry].to_s =~ /~~\z/
                    = link_to unmark_path(key: full_key), class: 'btn btn-xs btn-success unmark-key', remote: true, data: {method: 'DELETE'}
                      i.glyphicon.glyphicon-check
                  - else
                    = link_to mark_path(key: full_key), class: 'btn btn-xs btn-info mark-key', remote: true, data: {method: 'POST'}
                      i.glyphicon.glyphicon-flag
              .spinner
            - I18nO7r.languages.each do |l|
              td
                - val = store.lookup(l, (local[:key] + [local[:entry]]).join('.'))
                = hidden_field_tag "translations[#{ix}][#{l}][key]", local[:key].join('.')
                - if val.is_a?(Hash)
                  = text_area_tag "translations[#{ix}][#{l}][entry][#{local[:entry]}][html]", val[:html], class: 'form-control autosize html'
                - else
                  = text_area_tag "translations[#{ix}][#{l}][entry][#{local[:entry]}]", val, class: 'form-control autosize ' + (local[:entry].to_s.end_with?('html') ? 'html' : '')
      .panel-footer
        = submit_tag 'Speichern', class: 'btn btn-primary'
    - else
      .panel-footer
         | No Entries

app/views/i18n_o7r/keys/edit.html.slim
.modal.fade
  .modal-dialog
      .modal-content
        = form_tag(update_key_path(path: @path), method: :patch, id: 'update_key_form', remote: true)
          .modal-header
            button.close type='button' data-dismiss='modal' aria-label='Close'
              span aria-hidden='true' &times;
            h4.modal-title Edit key
          .modal-body
            .input-group
              span.input-group-addon
                = "#{@path.split('/')[0...-1].join('.').gsub('--', '/')}."
              = text_field_tag 'new_key', nil, required: true, class: 'form-control', placeholder: @path.split('/').last.gsub(/~~\z/, '')
          .modal-footer
            .spinner
            .update_key_buttons
              button.btn.btn-link type='button' data-dismiss='modal' Close
              = submit_tag 'Update', class: 'btn btn-primary', style: 'margin-top: 5px;'

app/views/i18n_o7r/markers/index.html.slim
- @keys ||= []
= render 'list_panel',
    panel_type: 'panel-default',
    title: "Markers",
    form_url: i18n_o7r.translations_path,
    details_url: ->(path) {i18n_o7r_translations_path(path)},
    locals: @locals,
    subtrees: nil,
    keys: [],
    store: @store,
    show_home_button: false

app/views/i18n_o7r/missing_translations/_tree.html.slim
- outer = outer
- if outer
  - @n = 0
- store.each do |k, v|
  - next if I18nO7r.excluded_subtrees.present? && I18nO7r.excluded_subtrees.any? { |t| k.to_s.start_with?(t) }
  - newkeys = [keys, k].flatten
  - case v
  - when Hash
    - c = v._deep_count {|v| v == nil ? 1 : 0 }
    - if c > 0
      - if outer
        - @n += c
      li
        => link_to i18n_o7r_translations_path(newkeys), class: 'btn btn-default btn-sm'
          tt
            - kk = newkeys.join('.')
            = "#{kk} (#{c})"
        ul
          = render 'tree', store: v, keys: newkeys
  - else
    / nothing!

app/views/i18n_o7r/missing_translations/index.html.slim
- content_for :tree
  = render 'tree', store: @store.translations[@lang.to_sym], keys: [], outer: true

.panel.panel-warning
  .panel-heading
    h3.panel-title #{@n} Missing translations for #{@lang}
  .panel-body
    .easy-tree
      ul
        = content_for :tree
/ javascript:
/   jQuery(function ($) {
/     $('.easy-tree').EasyTree({
/       selectable: false,
/       deletable: false,
/       editable: false,
/       addable: false
/     })
/   })

app/views/i18n_o7r/search/index.html.slim
- @keys ||= []
= render 'list_panel',
    panel_type: 'panel-default',
    title: "Search results",
    form_url: i18n_o7r.translations_path,
    details_url: ->(path) {i18n_o7r_translations_path(path)},
    locals: @locals,
    subtrees: nil,
    keys: [],
    store: @store,
    show_home_button: false

app/views/i18n_o7r/translations/index.html.slim
= render 'list_panel',
  panel_type: 'panel-default',
  title: "Translations for",
  form_url: request.path,
  details_url: ->(path) {i18n_o7r_translations_path(path)},
  entries: @entries,
  subtrees: @subtrees,
  keys: @keys,
  store: @store,
  locals: @entries.map{|k,v| {key: @keys, entry: k, value: v}},
  show_home_button: true

app/views/layouts/i18n_o7r/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title I18nO7r – Internationalization Organizer
    = stylesheet_link_tag I18nO7r.bootstrap_css_url, integrity: I18nO7r.bootstrap_css_integrity, crossorigin: "anonymous", media: "all"
    = stylesheet_link_tag 'i18n_o7r/application', media: "all"
    = javascript_include_tag I18nO7r.jquery_url, integrity: I18nO7r.jquery_integrity, crossorigin: "anonymous"
    = javascript_include_tag 'i18n_o7r/application'
    = javascript_include_tag I18nO7r.bootstrap_js_url, integrity: I18nO7r.bootstrap_js_integrity, crossorigin: "anonymous"
    = csrf_meta_tags
body
  nav class="navbar navbar-inverse navbar-fixed-top"
    div class="container"
      div class="navbar-header"
        button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
        a class="navbar-brand" href="#" I18n O7r
      div id="navbar" class="collapse navbar-collapse"
        ul class="nav navbar-nav"
          li: a href=i18n_o7r.translations_path Translations
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Missing Translations
              b.caret
            ul.dropdown-menu
              - I18nO7r.languages.each do |loc|
                li: a href=i18n_o7r.missing_translations_path(loc) = loc
          li
            a href=i18n_o7r.markers_path Marker
        = form_tag i18n_o7r.search_path, method: :get, class: 'navbar-form navbar-left', role: 'search'
            .input-group
              = search_field_tag 'query', params[:query], class: 'form-control', minlength: '3'
              .input-group-btn
                button.btn.btn-default type="submit"
                  span.glyphicon.glyphicon-search aria-hidden="true"

  .container style='margin-top: 70px;'
    = yield